# Generated by Django 3.2.5 on 2021-10-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transfer_info',
            new_name='transfer_ct',
        ),
    ]
