# Generated by Django 3.2.5 on 2021-10-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bank.branch'),
        ),
    ]
