# Generated by Django 3.2.5 on 2021-10-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bank', '0003_transaction_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transfer_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_ct',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_obj', to='contenttypes.contenttype'),
        ),
    ]
