# Generated by Django 3.2.5 on 2021-10-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bank', '0004_auto_20211005_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_type', to='contenttypes.contenttype'),
        ),
    ]
