version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=digify
      - DB_USER=root
      - DB_PASS=root

    command:
      sh -c " cd app &&
              ./manage.py wait_for_db &&
              ./manage.py makemigrations accounts&&
              ./manage.py makemigrations bank&&
              ./manage.py migrate &&
             ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=digify
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root